// Code generated by protoc-gen-go. DO NOT EDIT.
// source: aclpolicy.proto

package api

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Verdict int32

const (
	Verdict_ALLOW Verdict = 0
	Verdict_DENY  Verdict = 1
)

var Verdict_name = map[int32]string{
	0: "ALLOW",
	1: "DENY",
}

var Verdict_value = map[string]int32{
	"ALLOW": 0,
	"DENY":  1,
}

func (x Verdict) String() string {
	return proto.EnumName(Verdict_name, int32(x))
}

func (Verdict) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_867e1063938b2946, []int{0}
}

type Direction int32

const (
	Direction_INGRESS Direction = 0
	Direction_EGRESS  Direction = 1
	Direction_BOTH    Direction = 2
)

var Direction_name = map[int32]string{
	0: "INGRESS",
	1: "EGRESS",
	2: "BOTH",
}

var Direction_value = map[string]int32{
	"INGRESS": 0,
	"EGRESS":  1,
	"BOTH":    2,
}

func (x Direction) String() string {
	return proto.EnumName(Direction_name, int32(x))
}

func (Direction) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_867e1063938b2946, []int{1}
}

type NPMNetworkPolicy struct {
	Name  string            `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	IPSet map[string]*IPSet `protobuf:"bytes,2,rep,name=IPSet,proto3" json:"IPSet,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	ACLs  []*AclPolicy      `protobuf:"bytes,3,rep,name=ACLs,proto3" json:"ACLs,omitempty"`
	// Making this a podKey instead should be
	// use NPMPod obj
	Pods                 []string `protobuf:"bytes,4,rep,name=Pods,proto3" json:"Pods,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NPMNetworkPolicy) Reset()         { *m = NPMNetworkPolicy{} }
func (m *NPMNetworkPolicy) String() string { return proto.CompactTextString(m) }
func (*NPMNetworkPolicy) ProtoMessage()    {}
func (*NPMNetworkPolicy) Descriptor() ([]byte, []int) {
	return fileDescriptor_867e1063938b2946, []int{0}
}

func (m *NPMNetworkPolicy) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NPMNetworkPolicy.Unmarshal(m, b)
}
func (m *NPMNetworkPolicy) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NPMNetworkPolicy.Marshal(b, m, deterministic)
}
func (m *NPMNetworkPolicy) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NPMNetworkPolicy.Merge(m, src)
}
func (m *NPMNetworkPolicy) XXX_Size() int {
	return xxx_messageInfo_NPMNetworkPolicy.Size(m)
}
func (m *NPMNetworkPolicy) XXX_DiscardUnknown() {
	xxx_messageInfo_NPMNetworkPolicy.DiscardUnknown(m)
}

var xxx_messageInfo_NPMNetworkPolicy proto.InternalMessageInfo

func (m *NPMNetworkPolicy) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *NPMNetworkPolicy) GetIPSet() map[string]*IPSet {
	if m != nil {
		return m.IPSet
	}
	return nil
}

func (m *NPMNetworkPolicy) GetACLs() []*AclPolicy {
	if m != nil {
		return m.ACLs
	}
	return nil
}

func (m *NPMNetworkPolicy) GetPods() []string {
	if m != nil {
		return m.Pods
	}
	return nil
}

type AclPolicy struct {
	PolicyID             string     `protobuf:"bytes,1,opt,name=PolicyID,proto3" json:"PolicyID,omitempty"`
	PolicyName           string     `protobuf:"bytes,2,opt,name=PolicyName,proto3" json:"PolicyName,omitempty"`
	Comment              string     `protobuf:"bytes,3,opt,name=Comment,proto3" json:"Comment,omitempty"`
	SrcList              []*SetInfo `protobuf:"bytes,4,rep,name=SrcList,proto3" json:"SrcList,omitempty"`
	DstList              []*SetInfo `protobuf:"bytes,5,rep,name=DstList,proto3" json:"DstList,omitempty"`
	Target               Verdict    `protobuf:"varint,6,opt,name=Target,proto3,enum=api.Verdict" json:"Target,omitempty"`
	Direction            Direction  `protobuf:"varint,7,opt,name=Direction,proto3,enum=api.Direction" json:"Direction,omitempty"`
	Protocol             string     `protobuf:"bytes,8,opt,name=Protocol,proto3" json:"Protocol,omitempty"`
	SrcPortList          []*Ports   `protobuf:"bytes,9,rep,name=SrcPortList,proto3" json:"SrcPortList,omitempty"`
	DstPortList          []*Ports   `protobuf:"bytes,10,rep,name=DstPortList,proto3" json:"DstPortList,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *AclPolicy) Reset()         { *m = AclPolicy{} }
func (m *AclPolicy) String() string { return proto.CompactTextString(m) }
func (*AclPolicy) ProtoMessage()    {}
func (*AclPolicy) Descriptor() ([]byte, []int) {
	return fileDescriptor_867e1063938b2946, []int{1}
}

func (m *AclPolicy) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AclPolicy.Unmarshal(m, b)
}
func (m *AclPolicy) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AclPolicy.Marshal(b, m, deterministic)
}
func (m *AclPolicy) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AclPolicy.Merge(m, src)
}
func (m *AclPolicy) XXX_Size() int {
	return xxx_messageInfo_AclPolicy.Size(m)
}
func (m *AclPolicy) XXX_DiscardUnknown() {
	xxx_messageInfo_AclPolicy.DiscardUnknown(m)
}

var xxx_messageInfo_AclPolicy proto.InternalMessageInfo

func (m *AclPolicy) GetPolicyID() string {
	if m != nil {
		return m.PolicyID
	}
	return ""
}

func (m *AclPolicy) GetPolicyName() string {
	if m != nil {
		return m.PolicyName
	}
	return ""
}

func (m *AclPolicy) GetComment() string {
	if m != nil {
		return m.Comment
	}
	return ""
}

func (m *AclPolicy) GetSrcList() []*SetInfo {
	if m != nil {
		return m.SrcList
	}
	return nil
}

func (m *AclPolicy) GetDstList() []*SetInfo {
	if m != nil {
		return m.DstList
	}
	return nil
}

func (m *AclPolicy) GetTarget() Verdict {
	if m != nil {
		return m.Target
	}
	return Verdict_ALLOW
}

func (m *AclPolicy) GetDirection() Direction {
	if m != nil {
		return m.Direction
	}
	return Direction_INGRESS
}

func (m *AclPolicy) GetProtocol() string {
	if m != nil {
		return m.Protocol
	}
	return ""
}

func (m *AclPolicy) GetSrcPortList() []*Ports {
	if m != nil {
		return m.SrcPortList
	}
	return nil
}

func (m *AclPolicy) GetDstPortList() []*Ports {
	if m != nil {
		return m.DstPortList
	}
	return nil
}

type SetInfo struct {
	IPSet                *IPSet   `protobuf:"bytes,1,opt,name=IPSet,proto3" json:"IPSet,omitempty"`
	Included             bool     `protobuf:"varint,2,opt,name=Included,proto3" json:"Included,omitempty"`
	MatchType            string   `protobuf:"bytes,3,opt,name=MatchType,proto3" json:"MatchType,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetInfo) Reset()         { *m = SetInfo{} }
func (m *SetInfo) String() string { return proto.CompactTextString(m) }
func (*SetInfo) ProtoMessage()    {}
func (*SetInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_867e1063938b2946, []int{2}
}

func (m *SetInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetInfo.Unmarshal(m, b)
}
func (m *SetInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetInfo.Marshal(b, m, deterministic)
}
func (m *SetInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetInfo.Merge(m, src)
}
func (m *SetInfo) XXX_Size() int {
	return xxx_messageInfo_SetInfo.Size(m)
}
func (m *SetInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_SetInfo.DiscardUnknown(m)
}

var xxx_messageInfo_SetInfo proto.InternalMessageInfo

func (m *SetInfo) GetIPSet() *IPSet {
	if m != nil {
		return m.IPSet
	}
	return nil
}

func (m *SetInfo) GetIncluded() bool {
	if m != nil {
		return m.Included
	}
	return false
}

func (m *SetInfo) GetMatchType() string {
	if m != nil {
		return m.MatchType
	}
	return ""
}

type Ports struct {
	Port                 int64    `protobuf:"varint,1,opt,name=Port,proto3" json:"Port,omitempty"`
	EndPort              int64    `protobuf:"varint,2,opt,name=EndPort,proto3" json:"EndPort,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Ports) Reset()         { *m = Ports{} }
func (m *Ports) String() string { return proto.CompactTextString(m) }
func (*Ports) ProtoMessage()    {}
func (*Ports) Descriptor() ([]byte, []int) {
	return fileDescriptor_867e1063938b2946, []int{3}
}

func (m *Ports) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Ports.Unmarshal(m, b)
}
func (m *Ports) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Ports.Marshal(b, m, deterministic)
}
func (m *Ports) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Ports.Merge(m, src)
}
func (m *Ports) XXX_Size() int {
	return xxx_messageInfo_Ports.Size(m)
}
func (m *Ports) XXX_DiscardUnknown() {
	xxx_messageInfo_Ports.DiscardUnknown(m)
}

var xxx_messageInfo_Ports proto.InternalMessageInfo

func (m *Ports) GetPort() int64 {
	if m != nil {
		return m.Port
	}
	return 0
}

func (m *Ports) GetEndPort() int64 {
	if m != nil {
		return m.EndPort
	}
	return 0
}

func init() {
	proto.RegisterEnum("api.Verdict", Verdict_name, Verdict_value)
	proto.RegisterEnum("api.Direction", Direction_name, Direction_value)
	proto.RegisterType((*NPMNetworkPolicy)(nil), "api.NPMNetworkPolicy")
	proto.RegisterMapType((map[string]*IPSet)(nil), "api.NPMNetworkPolicy.IPSetEntry")
	proto.RegisterType((*AclPolicy)(nil), "api.AclPolicy")
	proto.RegisterType((*SetInfo)(nil), "api.SetInfo")
	proto.RegisterType((*Ports)(nil), "api.Ports")
}

func init() { proto.RegisterFile("aclpolicy.proto", fileDescriptor_867e1063938b2946) }

var fileDescriptor_867e1063938b2946 = []byte{
	// 492 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x93, 0x5d, 0x8b, 0xd3, 0x4c,
	0x14, 0xc7, 0x37, 0x49, 0xdb, 0x34, 0x27, 0x0f, 0xfb, 0x84, 0xb9, 0x1a, 0x8a, 0x2c, 0xa1, 0x88,
	0x94, 0x65, 0xe9, 0x45, 0x45, 0x11, 0xef, 0xea, 0xa6, 0x68, 0xa1, 0xdb, 0x2d, 0x93, 0xa2, 0x78,
	0x19, 0xa7, 0xa3, 0x86, 0x4d, 0x33, 0x61, 0x32, 0xab, 0xf4, 0xbb, 0xfa, 0x55, 0x04, 0x99, 0x33,
	0xd3, 0xb4, 0xb8, 0xde, 0x9d, 0x73, 0xfe, 0xbf, 0x93, 0xf3, 0x36, 0x81, 0xff, 0x0b, 0x5e, 0x35,
	0xb2, 0x2a, 0xf9, 0x61, 0xda, 0x28, 0xa9, 0x25, 0x09, 0x8a, 0xa6, 0x1c, 0xc5, 0x65, 0xd3, 0x0a,
	0x6d, 0x23, 0xe3, 0x5f, 0x1e, 0x24, 0xeb, 0xcd, 0xdd, 0x5a, 0xe8, 0x9f, 0x52, 0x3d, 0x6c, 0x10,
	0x26, 0x04, 0x7a, 0xeb, 0x62, 0x2f, 0xa8, 0x97, 0x7a, 0x93, 0x88, 0xa1, 0x4d, 0x5e, 0x43, 0x7f,
	0xb9, 0xc9, 0x85, 0xa6, 0x7e, 0x1a, 0x4c, 0xe2, 0x59, 0x3a, 0x2d, 0x9a, 0x72, 0xfa, 0x77, 0xe6,
	0x14, 0x91, 0x45, 0xad, 0xd5, 0x81, 0x59, 0x9c, 0x8c, 0xa1, 0x37, 0xbf, 0x5d, 0xb5, 0x34, 0xc0,
	0xb4, 0x4b, 0x4c, 0x9b, 0xf3, 0xca, 0xf2, 0x0c, 0x35, 0x53, 0x6f, 0x23, 0x77, 0x2d, 0xed, 0xa5,
	0x81, 0xa9, 0x67, 0xec, 0x51, 0x06, 0x70, 0xfa, 0x18, 0x49, 0x20, 0x78, 0x10, 0x07, 0xd7, 0x90,
	0x31, 0x49, 0x0a, 0xfd, 0x1f, 0x45, 0xf5, 0x28, 0xa8, 0x9f, 0x7a, 0x93, 0x78, 0x06, 0xf8, 0x61,
	0xcc, 0x60, 0x56, 0x78, 0xeb, 0xbf, 0xf1, 0xc6, 0xbf, 0x7d, 0x88, 0xba, 0x6a, 0x64, 0x04, 0x43,
	0x6b, 0x2d, 0x33, 0xf7, 0xa9, 0xce, 0x27, 0x57, 0x00, 0xd6, 0xc6, 0xc9, 0x7d, 0x54, 0xcf, 0x22,
	0x84, 0x42, 0x78, 0x2b, 0xf7, 0x7b, 0x51, 0x6b, 0x1a, 0xa0, 0x78, 0x74, 0xc9, 0x0b, 0x08, 0x73,
	0xc5, 0x57, 0x65, 0xab, 0x71, 0x80, 0x78, 0xf6, 0x1f, 0xf6, 0x92, 0x0b, 0xbd, 0xac, 0xbf, 0x4a,
	0x76, 0x14, 0x0d, 0x97, 0xb5, 0x1a, 0xb9, 0xfe, 0xbf, 0x38, 0x27, 0x92, 0xe7, 0x30, 0xd8, 0x16,
	0xea, 0x9b, 0xd0, 0x74, 0x90, 0x7a, 0x93, 0x4b, 0x87, 0x7d, 0x14, 0x6a, 0x57, 0x72, 0xcd, 0x9c,
	0x46, 0x6e, 0x20, 0xca, 0x4a, 0x25, 0xb8, 0x2e, 0x65, 0x4d, 0x43, 0x04, 0xed, 0x72, 0xbb, 0x28,
	0x3b, 0x01, 0x38, 0xb9, 0xb9, 0x37, 0x97, 0x15, 0x1d, 0xba, 0xc9, 0x9d, 0x4f, 0x6e, 0x20, 0xce,
	0x15, 0xdf, 0x48, 0x65, 0x7b, 0x8b, 0xb0, 0x37, 0xbb, 0x4f, 0x13, 0x6c, 0xd9, 0xb9, 0x6c, 0xe8,
	0xac, 0xd5, 0x1d, 0x0d, 0x4f, 0xe9, 0x33, 0x79, 0x2c, 0x20, 0x74, 0xf3, 0x99, 0x83, 0xd9, 0x07,
	0xe4, 0x3d, 0x3d, 0x98, 0x7d, 0x2a, 0x23, 0x18, 0x2e, 0x6b, 0x5e, 0x3d, 0xee, 0xc4, 0x0e, 0x0f,
	0x30, 0x64, 0x9d, 0x4f, 0x9e, 0x41, 0x74, 0x57, 0x68, 0xfe, 0x7d, 0x7b, 0x68, 0x84, 0x3b, 0xc0,
	0x29, 0x30, 0x7e, 0x05, 0x7d, 0x2c, 0x6e, 0x5f, 0x92, 0xb2, 0x35, 0x02, 0x86, 0xb6, 0xb9, 0xdc,
	0xa2, 0xde, 0x61, 0xd8, 0xc7, 0xf0, 0xd1, 0xbd, 0xbe, 0x82, 0xd0, 0xad, 0x95, 0x44, 0xd0, 0x9f,
	0xaf, 0x56, 0xf7, 0x9f, 0x92, 0x0b, 0x32, 0x84, 0x5e, 0xb6, 0x58, 0x7f, 0x4e, 0xbc, 0xeb, 0xe9,
	0xd9, 0x8e, 0x49, 0x0c, 0xe1, 0x72, 0xfd, 0x9e, 0x2d, 0xf2, 0x3c, 0xb9, 0x20, 0x00, 0x83, 0x85,
	0xb5, 0x3d, 0xc3, 0xbf, 0xbb, 0xdf, 0x7e, 0x48, 0xfc, 0x2f, 0x03, 0xfc, 0xa7, 0x5e, 0xfe, 0x09,
	0x00, 0x00, 0xff, 0xff, 0xb5, 0x7c, 0xe5, 0x1c, 0x78, 0x03, 0x00, 0x00,
}
