// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ipset.proto

package api

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SetType int32

const (
	SetType_Unknown                  SetType = 0
	SetType_NameSpace                SetType = 1
	SetType_KeyLabelOfNameSpace      SetType = 2
	SetType_KeyValueLabelOfNameSpace SetType = 3
	SetType_KeyLabelOfPod            SetType = 4
	SetType_KeyValueLabelOfPod       SetType = 5
	SetType_NamedPorts               SetType = 6
	SetType_NestedLabelOfPod         SetType = 7
	SetType_CIDRBlocks               SetType = 8
)

var SetType_name = map[int32]string{
	0: "Unknown",
	1: "NameSpace",
	2: "KeyLabelOfNameSpace",
	3: "KeyValueLabelOfNameSpace",
	4: "KeyLabelOfPod",
	5: "KeyValueLabelOfPod",
	6: "NamedPorts",
	7: "NestedLabelOfPod",
	8: "CIDRBlocks",
}

var SetType_value = map[string]int32{
	"Unknown":                  0,
	"NameSpace":                1,
	"KeyLabelOfNameSpace":      2,
	"KeyValueLabelOfNameSpace": 3,
	"KeyLabelOfPod":            4,
	"KeyValueLabelOfPod":       5,
	"NamedPorts":               6,
	"NestedLabelOfPod":         7,
	"CIDRBlocks":               8,
}

func (x SetType) String() string {
	return proto.EnumName(SetType_name, int32(x))
}

func (SetType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_abe00ff85a302de1, []int{0}
}

type IPSet struct {
	Name                 string     `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	HashedName           string     `protobuf:"bytes,2,opt,name=HashedName,proto3" json:"HashedName,omitempty"`
	Type                 SetType    `protobuf:"varint,3,opt,name=Type,proto3,enum=api.SetType" json:"Type,omitempty"`
	Members              []*Members `protobuf:"bytes,4,rep,name=Members,proto3" json:"Members,omitempty"`
	ReferCount           int32      `protobuf:"varint,5,opt,name=ReferCount,proto3" json:"ReferCount,omitempty"`
	Size                 int32      `protobuf:"varint,6,opt,name=Size,proto3" json:"Size,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *IPSet) Reset()         { *m = IPSet{} }
func (m *IPSet) String() string { return proto.CompactTextString(m) }
func (*IPSet) ProtoMessage()    {}
func (*IPSet) Descriptor() ([]byte, []int) {
	return fileDescriptor_abe00ff85a302de1, []int{0}
}

func (m *IPSet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IPSet.Unmarshal(m, b)
}
func (m *IPSet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IPSet.Marshal(b, m, deterministic)
}
func (m *IPSet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IPSet.Merge(m, src)
}
func (m *IPSet) XXX_Size() int {
	return xxx_messageInfo_IPSet.Size(m)
}
func (m *IPSet) XXX_DiscardUnknown() {
	xxx_messageInfo_IPSet.DiscardUnknown(m)
}

var xxx_messageInfo_IPSet proto.InternalMessageInfo

func (m *IPSet) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *IPSet) GetHashedName() string {
	if m != nil {
		return m.HashedName
	}
	return ""
}

func (m *IPSet) GetType() SetType {
	if m != nil {
		return m.Type
	}
	return SetType_Unknown
}

func (m *IPSet) GetMembers() []*Members {
	if m != nil {
		return m.Members
	}
	return nil
}

func (m *IPSet) GetReferCount() int32 {
	if m != nil {
		return m.ReferCount
	}
	return 0
}

func (m *IPSet) GetSize() int32 {
	if m != nil {
		return m.Size
	}
	return 0
}

type Members struct {
	Value                []byte   `protobuf:"bytes,1,opt,name=Value,proto3" json:"Value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Members) Reset()         { *m = Members{} }
func (m *Members) String() string { return proto.CompactTextString(m) }
func (*Members) ProtoMessage()    {}
func (*Members) Descriptor() ([]byte, []int) {
	return fileDescriptor_abe00ff85a302de1, []int{1}
}

func (m *Members) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Members.Unmarshal(m, b)
}
func (m *Members) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Members.Marshal(b, m, deterministic)
}
func (m *Members) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Members.Merge(m, src)
}
func (m *Members) XXX_Size() int {
	return xxx_messageInfo_Members.Size(m)
}
func (m *Members) XXX_DiscardUnknown() {
	xxx_messageInfo_Members.DiscardUnknown(m)
}

var xxx_messageInfo_Members proto.InternalMessageInfo

func (m *Members) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

func init() {
	proto.RegisterEnum("api.SetType", SetType_name, SetType_value)
	proto.RegisterType((*IPSet)(nil), "api.IPSet")
	proto.RegisterType((*Members)(nil), "api.members")
}

func init() { proto.RegisterFile("ipset.proto", fileDescriptor_abe00ff85a302de1) }

var fileDescriptor_abe00ff85a302de1 = []byte{
	// 305 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x91, 0xcf, 0x4e, 0xf2, 0x40,
	0x14, 0xc5, 0xbf, 0xa1, 0x2d, 0xfd, 0xb8, 0xfc, 0x49, 0xbd, 0x12, 0xed, 0xc2, 0x68, 0xc3, 0xc2,
	0x34, 0x2e, 0x58, 0xe8, 0x1b, 0x88, 0x0b, 0x09, 0x8a, 0x64, 0x50, 0xf7, 0x03, 0xbd, 0xc4, 0x06,
	0xe8, 0x4c, 0x3a, 0x43, 0x0c, 0xbe, 0x99, 0x0b, 0xdf, 0xcd, 0xcc, 0x80, 0xa1, 0xd1, 0xdd, 0x9d,
	0xf3, 0x3b, 0xe7, 0xce, 0x49, 0x2e, 0x34, 0x73, 0xa5, 0xc9, 0xf4, 0x55, 0x29, 0x8d, 0x44, 0x4f,
	0xa8, 0xbc, 0xf7, 0xc9, 0x20, 0x18, 0x4e, 0xa6, 0x64, 0x10, 0xc1, 0x1f, 0x8b, 0x35, 0xc5, 0x2c,
	0x61, 0x69, 0x83, 0xbb, 0x19, 0xcf, 0x01, 0xee, 0x85, 0x7e, 0xa3, 0xcc, 0x91, 0x9a, 0x23, 0x15,
	0x05, 0x13, 0xf0, 0x9f, 0xb7, 0x8a, 0x62, 0x2f, 0x61, 0x69, 0xe7, 0xba, 0xd5, 0x17, 0x2a, 0xef,
	0x6b, 0x32, 0x56, 0xe3, 0x8e, 0xe0, 0x25, 0x84, 0x8f, 0xb4, 0x9e, 0x51, 0xa9, 0x63, 0x3f, 0xf1,
	0xd2, 0xe6, 0xde, 0xb4, 0xde, 0x69, 0xfc, 0x07, 0xda, 0x9f, 0x38, 0x2d, 0xa8, 0x1c, 0xc8, 0x4d,
	0x61, 0xe2, 0x20, 0x61, 0x69, 0xc0, 0x2b, 0x8a, 0x6d, 0x37, 0xcd, 0x3f, 0x28, 0xae, 0x3b, 0xe2,
	0xe6, 0xde, 0x05, 0x84, 0xfb, 0x3d, 0xd8, 0x85, 0xe0, 0x55, 0xac, 0x36, 0xbb, 0xf6, 0x2d, 0xbe,
	0x7b, 0x5c, 0x7d, 0x31, 0x08, 0xf7, 0x75, 0xb0, 0x09, 0xe1, 0x4b, 0xb1, 0x2c, 0xe4, 0x7b, 0x11,
	0xfd, 0xc3, 0x36, 0x34, 0x6c, 0xff, 0xa9, 0x12, 0x73, 0x8a, 0x18, 0x9e, 0xc2, 0xf1, 0x88, 0xb6,
	0x0f, 0x62, 0x46, 0xab, 0xa7, 0xc5, 0x01, 0xd4, 0xf0, 0x0c, 0xe2, 0x11, 0x6d, 0xdd, 0xb2, 0x3f,
	0xd4, 0xc3, 0x23, 0x68, 0x1f, 0x62, 0x13, 0x99, 0x45, 0x3e, 0x9e, 0x00, 0xfe, 0x0a, 0x58, 0x3d,
	0xc0, 0x0e, 0x80, 0x4d, 0x66, 0x13, 0x59, 0x1a, 0x1d, 0xd5, 0xb1, 0x0b, 0xd1, 0x98, 0xb4, 0xa1,
	0xac, 0xe2, 0x0a, 0xad, 0x6b, 0x30, 0xbc, 0xe3, 0xb7, 0x2b, 0x39, 0x5f, 0xea, 0xe8, 0xff, 0xac,
	0xee, 0x0e, 0x75, 0xf3, 0x1d, 0x00, 0x00, 0xff, 0xff, 0x8e, 0x65, 0x0f, 0x46, 0xb7, 0x01, 0x00,
	0x00,
}
