FROM golang:1.8.1

RUN apt -y update && apt install -y zip unzip

RUN go get -d golang.org/x/sys/unix
RUN go get -d github.com/Microsoft/hcsshim
RUN go get -d github.com/containernetworking/cni/pkg/skel

COPY . /go/src/github.com/Azure/azure-container-networking

WORKDIR /go/src/github.com/Azure/azure-container-networking
